# Generated by Django 5.2.8 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='travelDates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
