# Generated by Django 5.2.8 on 2025-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_name_message_phone_message_traveldates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customDestination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='toDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
