# Generated by Django 5.2.8 on 2025-11-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_booking_customdestination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='travelDates',
            new_name='travel_dates',
        ),
    ]
