# Generated by Django 4.2.26 on 2025-12-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_traveldates_message_travel_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_destination_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
